# Generated by Django 3.1.7 on 2023-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('pemail', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('puid', models.CharField(max_length=50)),
                ('className', models.CharField(default=None, max_length=120)),
                ('subjectName', models.CharField(default=None, max_length=120)),
                ('chapterName', models.CharField(default=None, max_length=120)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('liked_users', models.TextField(default=' ')),
                ('disliked_users', models.TextField(default=' ')),
            ],
            options={
                'verbose_name_plural': 'posts',
                'db_table': 'post',
            },
        ),
    ]
