# Generated by Django 5.0.1 on 2024-01-30 00:57

import gdstorage.storage
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=post.models.user_files),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
