# Generated by Django 3.1.7 on 2023-05-10 20:11

import audiofiles.models
from django.db import migrations, models
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('Class', models.CharField(default='', max_length=100)),
                ('Subject', models.CharField(default='', max_length=120)),
                ('ChapterName', models.CharField(default='', max_length=100)),
                ('PDF', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=audiofiles.models.file_path)),
                ('AudioFile', models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=audiofiles.models.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'audiofiles',
            },
        ),
    ]
