# Generated by Django 4.2.1 on 2024-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
