# Generated by Django 4.2.1 on 2024-02-18 01:29

import audiofiles.models
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0002_audiofiles_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiles',
            name='AudioFile',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], '2020csb1110@iitrpr.ac.in'), gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], '2020csb1107@iitrpr.ac.in'))), upload_to=audiofiles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='audiofiles',
            name='PDF',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], '2020csb1110@iitrpr.ac.in'), gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], '2020csb1107@iitrpr.ac.in'))), upload_to=audiofiles.models.file_path),
        ),
    ]
