# Generated by Django 4.2.1 on 2024-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0004_remove_audiofiles_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='Class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
