# Generated by Django 4.2.1 on 2024-02-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0005_audiofiles_class'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('grade',), name='unique appversion'),
        ),
    ]
