# Generated by Django 4.2.1 on 2024-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0006_grade_unique_appversion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique appversion',
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('grade',), name='unique grade'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique subject'),
        ),
    ]
