# Generated by Django 4.2.1 on 2024-02-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0007_remove_grade_unique_appversion_grade_unique_grade_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique subject',
        ),
    ]
