# Generated by Django 4.2.1 on 2024-02-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0009_alter_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='name',
            new_name='chaptername',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subjectname',
        ),
    ]
