# Generated by Django 4.2.1 on 2024-02-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0003_alter_audiofiles_audiofile_alter_audiofiles_pdf'),
        ('audiofiles', '0010_rename_name_chapter_chaptername_and_more'),
    ]

    operations = [
    ]
