# Generated by Django 4.2.1 on 2024-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0011_merge_20240219_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_audiofile_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_pdf_available',
            field=models.BooleanField(default=False),
        ),
    ]
