# Generated by Django 4.2.1 on 2024-02-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0012_chapter_is_audiofile_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'admins',
            },
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='Author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='References',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='approvedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiofiles.admin'),
        ),
    ]
